---
- name: Deploy Maven Artifact
  hosts: local
  gather_facts: false
  become: yes
  become_user: devops

  tasks:
    - name: Ensure target directory exists
      file:
        path: "/tmp"
        state: directory
        mode: '0755'

    - name: Check if the artifact exists
      stat:
        path: "/var/lib/jenkins/workspace/Maven-Git-Jenkins-Ansible-FreeStyle/target/MyMavenApp-1.0-SNAPSHOT.jar"
      register: artifact_stat

    - name: Fail if the artifact does not exist
      fail:
        msg: "The artifact file does not exist!"
      when: not artifact_stat.stat.exists

    - name: Copy the artifact to the deployment directory
      copy:
        src: "/var/lib/jenkins/workspace/Maven-Git-Jenkins-Ansible-FreeStyle/target/MyMavenApp-1.0-SNAPSHOT.jar"
        dest: "/tmp/SNAPSHOT.jar"
